spring:
  application:
    name: "demo-application"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

server:
  port: 8443
  ssl:
    enabled:
      true
    key-store:
      classpath:server_cert1BIB23342.jks
    key-store-type:
      JKS
    key-store-password:
      ${KEY_STORE_PASSWORD}
    key-alias:
      server_cert1BIB23342

jwt:
  accessExpiration: 900000
  refreshExpiration: 604800000
  secret: ${JWT_SECRET}